tuple= (21,36,14,25)
tuple.count(25)
coordinates = (4, 5)
print(coordinates[0])
#coordinates = (4, 5)=10 wont work
coures = ['history','math','physics']
print(coures)
print(coures[2])
print(coures[-2])
print(coures[0:2])
coures.append('art')
coures.insert(0,'compscience')
coures.pop()
coures.reverse()
coures.sort()
